[profile.default]
src = "src"
test = "test"
out = "out"
libs = ["../lib"]
remappings = [
  "openzeppelin-contracts/=../lib/openzeppelin-contracts/",
  "chainlink/=../lib/chainlink-brownie-contracts/contracts/src/v0.8/",
]
